<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae4de175-21c3-4d03-9a3e-7f73d5f98e53</elementGuidId>
    <imagePath></imagePath>
    <name>button_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[9]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#finish</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'finish') and equals(@name,'finish') and equals(@class,'btn btn_action btn_medium cart_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium cart_button</value>
        <webElementGuid>da605e46-01c8-4487-88e6-0e74b68f57be</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>cabf8ffe-a780-42c2-b382-e2f388155368</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>5497e90b-5420-4d67-b29d-5c77e4782119</webElementGuid>
    </webElementProperties>
</WebElementEntity>