<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df7b7826-3a72-42db-8eb5-1b54f505d021</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-backpack</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-backpack') and equals(@name,'add-to-cart-sauce-labs-backpack') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>cccbaa3e-189c-4fac-aeea-443834c50346</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-backpack</value>
        <webElementGuid>0d247bff-e915-496c-b42a-6790ac6f25ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-backpack</value>
        <webElementGuid>d15e8aa0-7ca2-42df-b52f-0aa4f8e4f306</webElementGuid>
    </webElementProperties>
</WebElementEntity>